name: Canary Release

on:
  push:
    branches: [ canary ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:dist

      - name: Prepare packages
        run: yarn prepack

      - name: Set git email
        run: git config --global user.email "adrian@webiny.com"

      - name: Set git username
        run: git config --global user.name "doitadrian"

      - name: Create a release on GitHub
        run: yarn lerna version --conventional-prerelease --yes

      - name: Release packages to NPM
        run: yarn lerna publish from-package --dist-tag canary --yes

