name: Canary Release

on:
  push:
    branches: [ canary ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: canary

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:dist

      - name: Prepare packages
        run: yarn prepack

      - name: Create a release on GitHub
        run: lerna version --conventional-prerelease --yes

      - name: Create a release on GitHub
        run: lerna publish from-package --dist-tag canary
