name: Next Release

on:
  push:
    branches: [ next ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build-test-release:
    name: Build, test and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:dist

      - name: Prepare packages
        run: yarn prepack

      - name: Set git email
        run: git config --global user.email "adrian@webiny.com"

      - name: Set git username
        run: git config --global user.name "doitadrian"

      - name: Create a release on GitHub
        run: yarn lerna version --conventional-prerelease --yes

      - name: Release packages to NPM
        run: yarn lerna publish from-package --dist-tag next --yes

